### ISSUE TITLE
[Discussion] Avoid enabling 'HTTPS only' for applications with 'Always On' enabled

### ISSUE THREAD

**Issue by xt0rted** [Azure/app-service-announcements-discussions#28]
There wasn't a discussion issue for https://github.com/Azure/app-service-announcements/issues/78 so I wanted to start one.

I'm running with both HTTPS Only and Always On enabled, but I also have availability tests setup in app insights that hit the site every 5 minutes or so. This could be a good temporary fix for users wanting to use HTTPS Only while also having the site be always on.

**Comment by davidebbo** [comment]
Thanks for starting the discussion!

One caveat with your workaround is that if you have multiple instances, it will only hit (and wake up) one arbitrarily. So it probably won't work reliably unless you get fancier and make 'n' requests, each passing the right ARRAffinity cookie (not easy!).

**Comment by PureKrome** [comment]
And even then - how do we know what all the ARRAfinity cookies are, for all instances?

**Comment by davidebbo** [comment]
You can get the list of instance IDs (which are the cookie values) using ARM:

    GET /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Web/sites/{sitename}/instances?api-version=2016-08-01

You can use https://resources.azure.com/ to easily see what that looks like.

**Comment by MatthewSteeples** [comment]
On a similar thread to this (as I assume that the fix for this will be to allow the always on code to make requests over https) can something be added so that if a WebJob function is actively running that it keeps the website alive using something like IRegisteredObject? We don't need our continuous WebJob to be always on, but we do need it to stop terminating tasks that are in progress for longer than 15 minutes. If this is better handled in a separate issue then let me know and I can raise it there.

**Comment by davidebbo** [comment]
@MatthewSteeples That mostly a separate question. But anyway, it's not something that's possible. Continuous WebJobs require AlwaysOn, and that is not likely to change.

**Comment by MatthewSteeples** [comment]
Yes, I suppose fixing the always on issue will fix the issue that we're seeing. Basically we have some WebJobs that get shut down mid execution (we're assuming because of the same https setting)

**Comment by davidebbo** [comment]
@MatthewSteeples it's unlikely to be the same issue. WebJobs run under the scm site, which is not affected by this 'https only' flag (because it's always been https only).

Please start a separate thread on [forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) or SO to better discuss. Or you can open a Kudu issue as well if you prefer.

**Comment by davidebbo** [comment]
@whytoe yes, you can set the `httpsOnly` property on the site object. See [here](https://github.com/davidebbo/AzureWebsitesSamples/blob/61c7b330e83750cd4092625d082340d69f3a54ec/PowerShell/HelperFunctions.ps1#L66-L71) and [here](https://github.com/davidebbo/AzureWebsitesSamples/blob/61c7b330e83750cd4092625d082340d69f3a54ec/PowerShell/HelperFunctionsTest.ps1#L25) for a PowerShell sample. Just change `clientAffinityEnabled` to `httpsOnly`.

**Comment by flatproject** [comment]
I would like to know the same as @AlexKeySmith . "Diagnose and Solve Problems" says we shouldn't but the thread suggests that the problem is fixed. Even with "HTTPS Only" disabled and enforcing the 301 redirection from http to https at the application level doesn't seem to have the right effect according to the "Diagnose and Solve Problems" blade.

![image](https://user-images.githubusercontent.com/18282373/47090460-e05d6580-d21a-11e8-90c2-4733d0e5d631.png)

**Comment by beneuto** [comment]
This still appears to be an issue if using AAD Authentication.   Logs show AlwaysOn call to loopback address (::1) always resulting in 302 redirect.   HTTPS Only setting, web.config entries and setting Authentication to Allow Anyonymous Requests and handling with authorization.json file seem to have no effect.

**Comment by An0d** [comment]
> This still appears to be an issue if using App Service Authentication. Logs show AlwaysOn call to loopback address (::1) always resulting in 302 redirect. HTTPS Only setting, web.config entries and setting Authentication to Allow Anyonymous Requests and handling with authorization.json file seem to have no effect.

Hi,

I feel like I'm having the same problem. AlwaysOn with App Service Authentication does not seem to work properly...

**Comment by beneuto** [comment]
@An0d, check this out:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/8a90906f-45f2-4fa0-9067-24a7d01c70c5/azure-quotalways-onquot-is-not-working?forum=windowsazurewebsitespreview
