### ISSUE TITLE
[Discussion] Azure Functions Runtime 2.0 preview breaking changes

### ISSUE THREAD

**Issue by fabiocav** [Azure/app-service-announcements-discussions#64]
Discussion for the upcoming Azure Functions Runtime breaking change release

**Comment by AHWafaey** [comment]
Thanks for the update but we faced an issue to migrate existing resource groups which were built based on a previous runtime version 2.0.11933-alpha to 2.0.11946.0. The migration of existing Azure Java functions towards that runtime version was not working and we had to rollback due to that. 

although building a new resource group with a new java function based on latest runtime was working properly. 

As such, the question is -- Does it require removing the whole app and rebuilding it from scratch is the solution? or is it enough only to update the function app settings?

///Thx

**Comment by fabiocav** [comment]
Just updating the app setting is sufficient. If done now, this will leave you in the same state you’re currently in, but will avoid the automatic update to the next, breaking, release.

**Comment by willmorgan** [comment]
How do we install the storage bindings?

If we're already using the storage SDK in our Node apps' codebase, does it make sense to simply abandon the bindings altogether and read/write to the storage account programmatically, using the SDK?

**Comment by jeffhollan** [comment]
@willmorgan once the bits get released the process will be the same to install in app as [other extensions we have today](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#local-development-azure-functions-core-tools).  Ideally you should be able to open up your project locally and just run `func extensions install` and it will pull down right packages for you.

That said, nothing the binding does that you couldn't do with just SDK.  So if you prefer to just use SDK in code you can.

**Comment by nzthiago** [comment]
Nice! What is the expected timeline for it to roll out everywhere?

**Comment by willmorgan** [comment]
> once the bits get released the process will be the same to install in app as other extensions we have today.

@jeffhollan What's the ETA on the extensions being released? Will there be adequate time to test between the extension release, and the removal of the built-in bindings?

**Comment by davidebbo** [comment]
@willmorgan from the announcement:

> Version 2.0.11961-alpha will be available for 30 days after the deployment completes

So you'll have plenty of time. We don't have the exact date where it will be released, but it is coming soon.

**Comment by TurtleBeach** [comment]
You guys seem to do your best to confuse with releases. Friday evening (8:30 EDT) you published a notice about an imminent release; I came in Saturday intending to pin to 2.0.11933 and found that 2.0.11946 was already running in EAST US. Now you say pin to 2.0.11961 and it is NOT running in EAST US, I am leery of pinning to a future version, since I have already been burned multiple times on unclear functionality in releases. And acknowledging it is my ignorance, I still have no idea what you mean when you reference function extensions and what has to be done. I have Java functions. I can debug locally. I can deploy. I can monitor them. I am about to launch a site that relies on the functions. Where does an "extension" come in? What is going to break when suddenly 2.0.11961 gets pushed out. Could you not at minimum (a) tell us now that you will specifically tell us x (1? 2?) days before you plan to start rolling out a release; and then (b) not start the rollout before then. I understand I am and have been working with "preview" (for one year, I also note) - but that should not be taken as a free pass to do whatever you feel like when you start pushing this stuff out.
/Rant

**Comment by davidebbo** [comment]
@TurtleBeach the 'imminent' release was `2.0.11961-alpha`, and it is in fact deployed everywhere now (it was fully deployed on Friday night). That release does not have any breaking changes over the previous one (`2.0.11946-alpha`). If you have an app that says it's running an older build, try restarting it.

And while we don't know the exact day of the next release that has the breaking changes, the point of the announcement is that if you pin yourself to `2.0.11961-alpha`, you will be safe, and will then have plenty of time to get ready for the breaking release once it comes.

Does that help clear the confusion?

**Comment by TurtleBeach** [comment]
Why does the Azure portal tell me my functions in EAST US are running 2.0.11946??
FUNCTIONS_EXTENSION_VERSION is set to beta.

**Comment by davidebbo** [comment]
@TurtleBeach please see my previous response which covers that (i.e. try restarting it).

**Comment by TurtleBeach** [comment]
OK. Restart gets the runtime up to 2.0.11961. But I trust you see my frustration. Friday night I'm told to expect an update. Saturday morning I see that all my functions, which were on 2.0.11933 transitioned to 2.0.11946. Now you tell me that Friday everything supposedly went to 2.0.11961. What happened in between, and how am I supposed to divine that? But I do appreciate the clarification now and I will pin everything to 11961.

**Comment by TurtleBeach** [comment]
One final observation - after I pin to 2.0.11961-alpha, the portal now reports "A newer version is available (~2)". Am I to ignore that, and leave functions pinned to 2.0.11961-alpha, or should the pinned version be -beta?

**Comment by paulbatum** [comment]
Ignore the portal for now. If you use the syntax "beta' or "~2" you wont be pinned anymore. Unfortunately the portal does not fully understand pinning and will show confusing messages like this one.

**Comment by flowest** [comment]
I'd like to know how long Azure Functions v1 runtime will be supported?
Upgrading from v1 to v2 is not that easy, right? (because v1 is using .NET Framework, v2 is using .NET Core etc.)

**Comment by MisinformedDNA** [comment]
> > Version 2.0.11961-alpha will be available for 30 days after the deployment completes
> 
> So you'll have plenty of time. We don't have the exact date where it will be released, but it is coming soon.

30 days is not "plenty of time", especially if you are breaking a bunch of stuff.

Will you also be sending out an email to all Function v2 users so they know about this?

**Comment by MisinformedDNA** [comment]
@flowest I think they promised at least one year of v2 in GA, before v1 deprecation.

**Comment by paulbatum** [comment]
@flowest for some discussion of this topic see [here](https://github.com/Azure/Azure-Functions/issues/790). Doesn't make much sense to discuss it here.

@MisinformedDNA V2 is in preview and we have real world constraints that limit how long we can keep older versions available in Azure. I do not understand your assertion about the time window for these upgrades. I hope you agree that us releasing these previews, despite the pain of breaking changes and their frequency, is better than going dark for extended periods of time with no releases.

**Comment by justinyoo** [comment]
Hi, a couple of questions:

1. Do you plan to roll out this release to Australia on/after Aug 18th?
1. Does this release include the container deployment scenario through Azure Portal, which currently experiencing UI/UX bug?

**Comment by kenturley** [comment]
Hello, I have my function app pinned at 2.0.11857-alpha. This was because a subsequent release broke the ability to return message text in HTTP responses. Example: return new BadRequestObjectResult("Missing one or more required fields");   --pinning to 11857 was the documented workaround.

I have two questions,

1. Is that behavior fixed in 2.0.11961-alpha such that I can pin to that more recent version?

1. Should I be concerned that 11857 will be deprecated? Am I at risk by still being on it?


Thank you.

**Comment by davidebbo** [comment]
@kenturley Yes, that issues was fixed a while back. I highly suggest that you try to pin yourself to 2.0.11961-alpha and verify that all is well. You are definitely at risk by being pinned to that older build.

Generally, pinning is always meant to be temporary to help transition to the next build. So if you need to be pinned, you should always be actively looking at what it takes for you to run on the latest version and unpin yourself.

**Comment by kenturley** [comment]
@davidebbo Okay.... We'll work on getting ourselves upgraded.  Thank you for the quick reply.

**Comment by berndverst** [comment]
You can run this bash script to update all affected function apps in the current subscription. Switch subscriptions via `az account list` and `az account set --subscription XXXXX`

```bash

#!/bin/bash

APPS=$(az functionapp list --query "[].{group: resourceGroup, name: name}" --output tsv)

IFS=$'\n'
for APP in $APPS
do
  GROUP=$(echo $APP | cut -f 1)
  NAME=$(echo $APP | cut -f 2)
  VERSION=$(az functionapp config appsettings list -g $GROUP -n $NAME --query "[?name == 'FUNCTIONS_EXTENSION_VERSION'].value" --output tsv)

  if [ "$VERSION" = "~2" ] || [ "$VERSION" = "~beta" ] || [ "$VERSION" = "beta" ]; then
    echo "Function app $NAME with version $VERSION in group $GROUP is being updated."
    $(az functionapp config appsettings set -n $NAME -g $GROUP --settings FUNCTIONS_EXTENSION_VERSION=2.0.11961-alpha)
    echo "Restarting function app $NAME in group $GROUP."
    $(az functionapp restart -n $NAME -g $GROUP)
  fi

done
```

**Comment by JohnReeson** [comment]
Does it matter as locally I have seen the  host version is `2.0.11960.0`? See it on both cli downloaded by VS and that one installed by npm.

**Comment by jmsalvo** [comment]
I ran the command 'func extensions install' and this added a new extensions.csproj file with some references to nuget packages.  Is this to be expected?  I got the impression from this discussion this is all we should need to do to account for these upcoming breaking changes?  Since running that command my VSTS .net core build task succeeds, but the test task now fails to build.

**Comment by paulbatum** [comment]
@jmsalvo You will need to do that process again once we have released updated nuget packages and a new core tools release. We'll send an update once this is the case.

**Comment by dlalex83** [comment]
Hi, I've pinned all my apps to 2.0.11961-alpha on Friday night and was looking to test against the new version today so to remove the pin. I didn't really understand how to test the changes against the new version as my local function host version is 2.0.11960 (through VS tools, latest version installed 15.0.40617.0). Also, what the new version (referenced by the Beta setting) should now be?
I've now removed the pin from the deployed apps and revert back to Beta. The apps seem to be working fine. Can you please clarify if there's something else I should do? Thanks

**Comment by paulbatum** [comment]
@dlalex83 Please keep yoru app pinned. We've delayed the release by a few days as we've found some regressions that need to be addressed. As a result we haven't released updated core tools or NuGet packages yet, which explains why you're unable to test with the latest bits at the moment. We'll update the announcement once the new bits are available.

**Comment by evenancio** [comment]
Not sure if this is the right place to report that, but all of sudden our deploys start failing after Deployment Center has been updated. That's weird because it was working a few hours ago.

Although our app functions are pinned to 2.0.11961-alpha, the Deployment Center Logs are saying "Your function app is targeting V1, but Azure host has function version V2, \r\nplease change the version using the portal or update your 'FUNCTIONS_EXTENSION_VERSION' appsetting and retry" during the "Preparing deployment for commit id..." phase.

We already tried to disconnect and redo the integration with VSTS, but no luck so far. Do someone know what is going on? I'm freaking out because of that.

In addition, we have some App Functions integrated with VSTS.

**Comment by dlalex83** [comment]
@evenancio just had the same problem on one of our function apps (the latest I've deployed onto azure, 1 week ago or so). I'm deploying from BitBucket and the exact same codebase works fine when deploying against a different function app in azure. I've disconnected and re attached to Bitbucket fixed it but the next build I've triggered broke with the same message.

**Comment by dlalex83** [comment]
The project is using v2. It was working fine until this morning. I've deployed the same project against a different function app (need it in 2 different regions) and it's working fine.

**Comment by davidebbo** [comment]
@dlalex83 Trying to make sure I fully understand this: did the issue start happening when you changed `FUNCTION_EXTENSION_VERSION` from `beta` to `2.0.11961-alpha`, or is it not related to this? i.e. for investigation purpose, if you set it back to `beta`, do you still get this error?

**Comment by davidebbo** [comment]
@dlalex83 One more question: look in your .csproj. Does it contain `<AzureFunctionsVersion>v2</AzureFunctionsVersion>`, as in [this sample](https://github.com/davidebbo-test/FunctionAppVS2017v2/blob/master/FunctionAppVS2017v2/FunctionAppVS2017v2.csproj)? This is what Kudu looks like to determine if it's a v2 app.

**Comment by dlalex83** [comment]
Yep it does. I might try to reprovision the function app. Very weird though.

**Comment by davidebbo** [comment]
@dlalex83 Were you able to test whether setting it back to `beta` made a difference? That would help isolate. Also, if you can share the name of a function app that is currently in the state where it gives this deployment error, it would help us investigate. Thanks!

**Comment by dlalex83** [comment]
I did set it back to beta but didn't help. Function name is: lts-scraper-downloader-us. Thanks for looking into it!

**Comment by davidebbo** [comment]
@dlalex83 ok, the issue has been identified. For now, you can work around by setting `KUDU_EXTENSION_VERSION` to `75.10629.3460` in your App Settings. We will push a fix hopefully later today, at which point you can remove this.

Also remember to set `FUNCTION_EXTENSION_VERSION` back to `2.0.11961-alpha`, as that was in fact unrelated to this issue.

**Comment by dlalex83** [comment]
Great, that worked. Thanks. It'd be great if you can announce the fix. Thanks!

**Comment by evenancio** [comment]
Hi @dlalex83 @davidebbo!

After setting KUDU_EXTENSION_VERSION, all our functions apps got back to work again!

Thank you

**Comment by evenancio** [comment]
Hi @davidebbo

I'd tried to redeploy one of our last commits after removing KUDU_EXTENSIONS_VERSION, but during the process we got the following message: "Failed to redeploy deployment _Function_App_Name_. The gateway did not receive a response from 'Microsoft.Web' within the specified time period". So we tried again and it worked as expected. It looks like everything is going well now. Not sure if this information is important for you, just telling my experience.

Sorry for posting this issue in the wrong place. Unfortunately I didn't find any other place to report this problem, since I had assumed it was related to Functions App/Deployment Center.

Thanks! Your help was much appreciated!

**Comment by davidebbo** [comment]
@evenancio not sure what happened there, but I would say it's some hiccup that is not related to the Kudu issue. If you see this more, please open a Kudu issue (https://github.com/projectkudu/kudu) and we'll discuss further.

**Comment by jdneo** [comment]
Hi team,

May I ask the ETA of the new runtime release? We need this information to schedule our Maven tooling updating plan.

/cc @Flanker32

Thanks

**Comment by paulbatum** [comment]
Deployment is starting today and will continue through tomorrow (8/30) at least.

**Comment by markheath** [comment]
I've updated my nuget packages to the new versions:

```
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.6.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.SendGrid" Version="3.0.0-beta5" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.0-beta8" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.19" />
  </ItemGroup>
```

but now I can't run locally from Visual Studio. I just get this error

```
A ScriptHost error has occurred
System.Private.CoreLib: No parameterless constructor defined for this object
```

Presumably there is updated VS tooling / Core Tools needed as well? Is there an ETA for this? Or is there some other problem?

**Comment by Meyce** [comment]
After performing the updates from https://github.com/Azure/app-service-announcements/issues/129, I've had to go to Kudu/Process Explorer, and kill the w3sp/node.exe process for all my Azure Function apps for them to use the new extension .dlls.

Also, the portal is still installing the old extension dlls. So if you create a new function through the portal, you still need to go through the steps in issue/129.

At least that has been my experience with javascript/node functions using service bus triggers.

**Comment by klesouza** [comment]
I keep getting 
`Error:

Function ... Error: The binding type(s) 'queueTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.
Session Id: 3c30f11bc5d246ebb797fdd9bd1255eb`

I've update all the libraries and tried the steps describe by Meyce.

**Comment by justinyoo** [comment]
It seems that the new runtime has rolled out to the Australia Southeast region. My function V2 instance worked perfectly fine until yesterday. However, today it suddenly started throwing 401 error. I quickly dug into the issue and found that most (not all) my function endpoints have their access key changed.

Here are my questions:

1. Access key changing, is it an expected behaviour?
1. I usually get the access key through the ARM template function, `listSecrets()`. However, it still returns the old key, which seem to be cached in somewhere.

Would you be able to look at this issue, please?

**Comment by will-beta** [comment]
IExtensionConfigProvider doesn't work now!
``` c#
    public class InjectConfiguration : IExtensionConfigProvider
    {
        public InjectConfiguration()
        {

        }
        public void Initialize(ExtensionConfigContext context)
        {
            throw new NotImplementedException();
        }
    }
```

**Comment by paulroub** [comment]
It's not clear how (or if) to apply the extension-installation guidance to a zip-deployed JavaScript function app. Adding extensions.csproj and redeploying has no apparent effect - still in "queueTrigger binding unknown" mode. I'd swear the previous breaking-change guidance implied that HTTP and Storage bindings were pre-installed in production and wouldn't need extra steps. We're stuck and would love not to rollback to the alpha -- any suggestions?

**Comment by danielaene** [comment]
Hello!
We are using the following setup: we have a logic apps that it’s calling azure functions written in java. The functions used runtime 2.0.11857-alpha.
After the rollout of azure functions runtime 2.0.12050 done today, we also updated our functions to be compatible with the new runtime (use azure-functions-java-library 1.0.0-beta-5 and azure-functions-maven-plugin 1.0.0-beta-5). We created new functions with the new azure functions runtime and we tried to integrate it with the logic app but we receive the following error:
{code}
{
'error': {
'code': 'InvalidFunctionType',
'message': 'The function '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{siteName}/functions/{functionName}' cannot be called from a logic app. It must be a generic JSON webhook function or a standard http trigger function.'
}
}
{code}
To exclude that it was a problem with our code, we’ve tried the following setup where we encounter the same error:
1. Generate a new java functions project using azure archetype from https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-java-maven
2. Deploy the functions
3. Create a new logic app that it’s calling the function
Do you know why the integration between logic apps and functions doesn’t work anymore for azure functions runtime 2.0.12050? Or do you know what runtime we could use to be able to invoke functions from logic apps ?

**Comment by brettsam** [comment]
@will-beta the extension-loading pipeline has changed and we haven't documented it yet. I can give you a quick rundown (also see the changes we've made to the core extensions [here](https://github.com/Azure/azure-webjobs-sdk-extensions/tree/dev/src) for examples).

Here's some info from CosmosDB, specifically

You'll need an `IWebJobsStartup`, which is registered via the `WebJobsStartup` assembly attribute: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB/CosmosDBWebJobsStartup.cs

From there, you can call registration methods on the `IWebJobsBuilder`, which is where you'll register the `IExtensionConfigProvider` and any other services you need: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB/Config/CosmosDBWebJobsBuilderExtensions.cs

**Comment by brettsam** [comment]
@justinyoo -- can you share your Function App name with me ([or you can share it privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately))?

**Comment by brettsam** [comment]
@klesouza -- You may be missing the new storage extension. Storage bindings are no longer a built-in part of the Functions host and need to be installed separately.

From https://github.com/Azure/app-service-announcements/issues/129:
> If you have functions that work with Azure Storage (queue/tables/blob) either with triggers, input bindings or output bindings, you'll need to reference the new Microsoft.Azure.WebJobs.Extensions.Storage extension.

**Comment by jmsalvo** [comment]
I thought I made all the necessary updates following the 'breaking changes notice' details, but I am seeing this error "No job functions found.  Try making your job classes and methods public.  If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).  Then, I see "the binding types are not registered.  Please ensure the type is correct and the binding extension is installed".  As far as I am aware, I have all the extensions installed.  Not sure what is meant by 'startup code', I presume I'm missing some configuration or setup that is now required in my function?

**Comment by brettsam** [comment]
@jmsalvo -- Where are you seeing this -- is it when running locally in Visual Studio? Does it say which binding types are not registered?

If it's in VS, did you verify that it's running the latest bits (you should see a message with version 12050, like  `Starting Host (HostId=____, InstanceId=____, Version=2.0.12050.0)`).

**Comment by jmsalvo** [comment]
I'm running locally in VisualStudio, I see a 'Starting Host' message indicating the Functions Runtime Version is 2.0.12050.0.  The binding types the message suggests are not registered are: activityTrigger, eventGridTrigger and orchestrationTrigger.

**Comment by brettsam** [comment]
@jmsalvo -- can you show me all of your referenced packages? Either with a screenshot or by opening the .csproj and copy/pasting the PackageReferences. I'll see if I can reproduce this.

**Comment by dlalex83** [comment]
@will-beta posted a comment [here](https://github.com/Azure/azure-functions-core-tools/issues/684#issuecomment-417739149) with the solution.

**Comment by jmsalvo** [comment]
The following are the referenced packages:
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.1-beta2" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.6.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.0.0-beta4" />
<PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.0.0" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.19" />

**Comment by brettsam** [comment]
@jmsalvo -- we may have to go back-and-forth with some questions to get you fixed so I created a separate issue that we can use for that: https://github.com/Azure/Azure-Functions/issues/928

**Comment by mhoeger** [comment]
@paulroub - The bin folder is required for you to run functions with bindings. There are some deployment methods (deploying through Kudu, for example) that aumatically build from extensions.csproj and create a bin folder. Portal development is another example where the bin folder is automatically generated. 

Since you are deploying from Run-From-Zip (now re-branded as run-from-package), you will need to include the bin folder in your packaged zip. This is very similar to how node_modules are treated in run from zip. As an aside, we don't recommend adding the contents of the bin folder itself to source control, rather you source control the files that determine the contents of the bin folder (extensions.csproj) and `func extensions install` as part of building your package.

Previously, storage bindings were built-in to the functions runtime. However, the most recent runtime de-couples storage bindings from the runtime itself. HTTP triggers will work the same. Please let me know if you have any issues with any of this!!

**Comment by paulroub** [comment]
@mhoeger No issues, unfortunately that doesn't help (although it *is* now necessary, it's not sufficient in our case). Judicious tweaking of the `Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator` per Fabio and Anthony Chu on Twitter got our deploy to at least create/populate extensions.json properly -- but still the error persists.

**Comment by mhoeger** [comment]
@paulroub - are you running all of this through VS Code (func CLI)? We just deployed the npm package (per[ Paul's comment](https://github.com/Azure/app-service-announcements/issues/129#issuecomment-417532064)), so any local building you did > 35 minutes ago would not install the storage sdk correctly. Could you confirm which version of azure-functions-core-tools you're using? (expectation is 2.0.1-beta.37)

**Comment by paulroub** [comment]
@mhoeger All of this is being done through scripts and the Azure cli. Core tools 2.0.1-beta.35 at the moment; I'll see if updating changes things.

**Comment by paulroub** [comment]
@mhoeger   2.0.1-beta.35 seems to be the latest available via homebrew at the moment. Will rebuilding with that still get the latest npm package, or do I need to rebuild the core tools from source?

**Comment by jmsalvo** [comment]
Has anyone encountered issues using the EventGridTrigger attribute.  I'm running my Azure function locally and when I post to the EventGrid webhook endpoint I'm seeing a 404 Not Found status code.  I haven't encountered this before, but can't say with certainty it is related to these updates.

**Comment by jmsalvo** [comment]
At some point, it appears the local EventGrid webhook endpoint changed from http://localhost:7071/runtime/webhooks/EventGridExtensionConfig?functionName={functionname} to http://localhost:7071/runtime/webhooks/EventGrid?functionName={functionname}.  Not sure if it was related to these updates or not.

**Comment by mhoeger** [comment]
@paulroub - could you `brew upgrade azure-functions-core-tools` again? 2.0.1-beta.37 (with corresponding runtime version 2.0.12050) was not there before, but it should be now! Then, running `func host start` will give you the same behavior you see in Azure (meaning you should see the same errors you reported). To fix them, please run `func extensions install`. The extensions.json should update correctly and if you run `func host start` again, everything should work as expected. Please zip and deploy these newly produced bits.

**Comment by mhoeger** [comment]
@danielaene - since you were running on 2.0.11857-alpha, I think there's a confounding factor of other breaking releases between that time: https://github.com/Azure/app-service-announcements/issues/132

Can you also provide more details on what your java function is? Is it an HTTP triggered function?

**Comment by jmsalvo** [comment]
I'm experiencing issues adding an Event Grid subscription to my Azure function in the portal.  When I click the link 'Add Event Grid Subscription' in my Azure function, the subscriber endpoint contains EventGridExtensionConfig and if I leave this 'as-is' the deployment fails with an 'Attempt to validate the endpoint failed' message.  If I update the URL manually to EventGrid vs EventGridExtensionConfig it then deploys successfully, but I now can't seem to change the default Event Types from 'All' to a specific event type.  I uncheck 'Subscribe to all event types' and enter a specific event type and then save, but the deployment never seems to complete. I keep seeing the message 'Deployment of your Event Subscription is proceeding' and the event type isn't updated.

**Comment by mhoeger** [comment]
@btardif / @hartra344 / @agruning (portal folks i could find easily!) - the issue above posted by @jmsalvo feels like a portal bug / break with newest v2. could any of you investigate?

**Comment by mieliespoor** [comment]
When I debug, I get the error:
`Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.`

![image](https://user-images.githubusercontent.com/5008243/44944493-dea52300-adcf-11e8-9e35-c55f937dc03b.png)

I have  2.2.0-preview1-35029 installed (last updated June 18, 2018):
`    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.0-beta8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.2.0-preview1-35029" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.19" />`

When will we have access to the latest version of the package?

**Comment by justinyoo** [comment]
@brettsam Sure. Here's my last successful function endpoint:

* 2018-08-31 10:53:55.909 (UTC)
* Executing 'GetPollingWatermarkHttpTrigger' (Reason='This function was programmatically called via the host APIs.', Id=07cc0d72-9a5c-4b0b-9302-160d8acfe776)

**Comment by paulroub** [comment]
@mhoeger After updating to the .37 release, and running `func extensions install` (and removing `bin` and `obj` beforehand), `func host start` quits after failing to load/find kernel32, seemingly in a Microsoft.ApplicationInsights... module)

We *are* using the `applicationinsights` NPM module (v1.0.4), but we never get far enough in initialization to even *register* our functions, let alone call them, so I doubt that's related.

> System.DllNotFoundException: Unable to load shared library 'kernel32' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libkernel32, 1): image not found  
>    at Microsoft.ApplicationInsights.SnapshotCollector.NativeMethods.GetModuleHandleW(String lpModuleName)  
>    at Microsoft.ApplicationInsights.SnapshotCollector.ProductionBreakpoints.PssSnapshot.IsPssCaptureSnapshotApiPresent()  
>    at Microsoft.ApplicationInsights.SnapshotCollector.SnapshotCreator..ctor(SnapshotCollectorConfiguration configuration, RuntimeEnvironment runtimeEnvironment, IUploader uploader)  
>    at Microsoft.ApplicationInsights.SnapshotCollector.PlatformServices..ctor(SnapshotCollectorConfiguration configuration)  
>    at Microsoft.ApplicationInsights.SnapshotCollector.SnapshotCollectorTelemetryProcessor..ctor(ITelemetryProcessor nextTelemetryProcessor, IPlatformServices platformServices, SnapshotCollectorConfiguration configuration)  
>    at Microsoft.ApplicationInsights.SnapshotCollector.TelemetryProcessorChainBuilderExtensions.<>c__DisplayClass0_0.<UseSnapshotCollector>b__0(ITelemetryProcessor previousProcessor)  
>    at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChainBuilder.Build()  
>    at Microsoft.Extensions.DependencyInjection.ApplicationInsightsServiceCollectionExtensions.SetupTelemetryConfiguration(TelemetryConfiguration configuration, String instrumentationKey, SamplingPercentageEstimatorSettings samplingSettings, SnapshotCollectorConfiguration snapshotCollectorConfiguration, ITelemetryChannel channel, IEnumerable`1 telemetryInitializers, IEnumerable`1 telemetryModules, IApplicationIdProvider applicationIdProvider, LoggerFilterOptions filterOptions) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\Extensions\ApplicationInsightsServiceCollectionExtensions.cs:line 204  
>    at Microsoft.Extensions.DependencyInjection.ApplicationInsightsServiceCollectionExtensions.<>c.<AddApplicationInsights>b__1_2(IServiceProvider provider) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\Extensions\ApplicationInsightsServiceCollectionExtensions.cs:line 86  
>    at DryIoc.Microsoft.DependencyInjection.DryIocAdapter.<>c__DisplayClass3_0.<RegisterDescriptor>b__0(IResolverContext r) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\DryIocAdapter.cs:line 156  
>    at DryIoc.Registrator.<>c__DisplayClass27_0.<RegisterDelegate>b__0(IResolverContext r) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 4530  
>    at DryIoc.Factory.<>c__DisplayClass26_1.<ApplyReuse>b__2() in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6584  
>    at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7825  
>    at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7810  
>    at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6583  
>    at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6544  
>    at DryIoc.Factory.GetDelegateOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6611  
>    at DryIoc.DelegateFactory.GetDelegateOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7719  
>    at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 210  
>    at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 195  
>    at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs:line 96  
>    at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs:line 74  
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)  
>    at Azure.Functions.Cli.Diagnostics.LoggingBuilder.<>c.<Configure>b__0_1(IServiceProvider provider)  
>    at DryIoc.Microsoft.DependencyInjection.DryIocAdapter.<>c__DisplayClass3_0.<RegisterDescriptor>b__0(IResolverContext r) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\DryIocAdapter.cs:line 156  
>    at DryIoc.Registrator.<>c__DisplayClass27_0.<RegisterDelegate>b__0(IResolverContext r) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 4530  
>    at DryIoc.Factory.<>c__DisplayClass26_1.<ApplyReuse>b__2() in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6584  
>    at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7825  
>    at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7810  
>    at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6583  
>    at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6544  
>    at DryIoc.Factory.GetDelegateOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6611  
>    at DryIoc.DelegateFactory.GetDelegateOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7719  
>    at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 290  
>    at lambda_method(Closure , IResolverContext )  
>    at DryIoc.Factory.<>c__DisplayClass26_1.<ApplyReuse>b__2() in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6584  
>    at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7825  
>    at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7810  
>    at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6583  
>    at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6544  
>    at DryIoc.WrappersSupport.GetArrayExpression(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 2883  
>    at DryIoc.ExpressionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7675  
>    at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6534  
>    at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7059  
>    at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6534  
>    at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7059  
>    at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6534  
>    at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7059  
>    at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6534  
>    at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7059  
>    at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6534  
>    at DryIoc.Factory.GetDelegateOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6611  
>    at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 210  
>    at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 195  
>    at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs:line 96  
>    at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetRequiredService(Type serviceType) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs:line 79  
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)  
>    at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.BuildHost(Boolean isOffline, Boolean skipHostJsonConfiguration) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs:line 218  
>    at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.StartHostAsync(CancellationToken cancellationToken, Int32 attemptCount, Boolean skipHostJsonConfiguration) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs:line 85

**Comment by notorioustech** [comment]
Function apps and durable functions in existing Logic Apps throws unauthorized errors.
The fix is to add a NEW function (or one not already in the logic app - re-adding same didn't fix), save run. Edit remove, now fixed.

**Comment by jeffhollan** [comment]
Thanks - we are aware there are instances where upgrading could reset your HTTP keys and are investigating now. If it happens just re-save the workflow (requires some small change in definition you could undo later) and it will refetch keys

**Comment by justinyoo** [comment]
@jeffhollan I'm having a similar issue with Logic Apps. However the difference from @notorioustech is I'm using ARM template function, `listSecrets()` to get the function access key. It still fetches the old one. What could you be the workaround on this?

**Comment by justinyoo** [comment]
@jeffhollan I did further investigation from my side as well.

* I did manually renew the defected function endpoint, whether it resets any cached key or not. But it still returns the old function access key through the ARM template function, `listSecrets()`.
* I invoked the REST API to get the function access key using [this approach](https://blog.mexia.com.au/dynamic-access-to-azure-functions-keys-without-kudu-dependencies), I'm able to get the new function access key.

It seems that the ARM template function gets the key not directly from the REST API call.

**Comment by pvto** [comment]
We have an issue with nodejs app deployed from VSTS.  The app stopped working over weekend.  

As per instructions, we updated host.json, added app setting FUNCTIONS_WORKER_RUNTIME=node, and finally added functions-extensions/extensions.csproj file to enable queueTrigger input.

Deployment indicates success, but now all functions have disappeared from under the app. With Kudu console, I can see that code is still deployed, but the functions don't appear to be functioning any more.

Probably missing something obvious here. However we can't figure out what to do next.

**Comment by pvto** [comment]
We got missing functions fixed by moving extensions.csproj from functions-extensions/ to app root folder.

An incompatible toolage version with "func extensions install" seems to cause this.

**Comment by klesouza** [comment]
@brettsam I've update SDK also installed the new required packages for Storage extensions. (I can see using the console everything is in there)
I can run locally using the latest version perfectly fine. 
I've tried stopping the function app, updating my zip URL, killing all process running and then starting my function app again, but I keep getting the same message. 
Not sure how to fix it.

**Comment by brettsam** [comment]
@paulroub -- in reference to your AppInsights exception. Are you running this on Windows? If you disable the SnapshotCollector in host.json with this, does it work?
```
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "snapshotConfiguration": {
                "isEnabled":  false
            }
        }
    }    
}
```

**Comment by paulroub** [comment]
@brettsam No, our local testing is on macOS. Tried disabling the snapshots just in case, but nothing changes.

**Comment by brettsam** [comment]
@paulroub -- Thanks for trying that. I assume that you're enabling App Insights locally with APPINSIGHTS_INSTRUMENTATIONKEY? If you remove that, does your host start up? I've opened up https://github.com/Azure/azure-webjobs-sdk/issues/1877 to track this, so please follow along there (I'll likely have some more questions).

**Comment by paulroub** [comment]
@brettsam Actually, no -- `APPINSIGHTS_INSTRUMENTATIONKEY` is *not* set in our test environment (at least, not by us -- and I don't think this would be set on our behalf by the Azure libraries).

**Comment by mieliespoor** [comment]
@brettsam I uninstalled the reference and even installed v2.1.0, but then in both cases I get this error:
`System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.`

**Comment by arkiaconsulting** [comment]
I had an error saying that "queueTrigger" was not registered (.Net). I installed locally the pre-release NuGet for storage, redeploy, and voilà. check [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue#packages---functions-2x)

**Comment by davidebbo** [comment]
There are too many distinct things being discussed in this thread, and it's hard to track/respond properly. Please open a separate issue on https://github.com/Azure/azure-functions-host for each distinct issue that you are having (you can post a link from here). We will get to all of them. Thanks!

**Comment by davidebbo** [comment]
@shurane it should be set to `~2`.

**Comment by klesouza** [comment]
I reported that was getting errors about the extensions not being registered even after following all the steps described in the docs.
`Function (...) Error: The binding type(s) 'queueTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.`
Today I found out what was missing, in case someone else still has the same problem:

Because I was packing my function inside a docker container to generate to zip file, it wasn't generating the `extensions.json` file. I had to add the package `Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator` manually to my project and it's working now.

**Comment by dabutvin** [comment]
Is there a date that `2.0.11961-alpha` will no longer be available? From following this thread it looks like `9/30/2018`. Just wanted to check and make sure. Thanks :)

**Comment by paulbatum** [comment]
@dabutvin yup thats correct.

**Comment by numb3rss** [comment]
Hello,

I'm also experiencing issues adding an Event Grid subscription to my azure function in the portal.

{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "Url validation",
        "message": "The attempt to validate the provided endpoint https://__.azurewebsites.net/runtime/webhooks/EventGrid failed. For more details, visit https://aka.ms/esvalidation."
      }
    ]
  }
}

I can't validate my subscriber endpoint, however i update my url manually like @jmsalvo suggested before. It is also related here : https://github.com/Azure/app-service-announcements/issues/129.

Here is my url endpoint : https://___.azurewebsites.net/runtime/webhooks/EventGrid?functionName=*********&code=*********

I tried many scenariis, i check 'Subscribe to all event types' first and then uncheck and specify event type. But deployment failed all the time. What am I doing wrong ?

Thanks.

**Comment by jeffhollan** [comment]
@brandonh-msft VS for mac team working on it this sprint.  They are hopeful they can get it into VS for Mac 7.6 but if not would be in Mac 7.7 preview 3

**Comment by brian-toniq** [comment]
Has the logging logic changed? I used to be able to see the exception details when a function failed, but now I only see a general error message that it failed. I have changed the host.json file to the new logging structure and tried various combinations but I still can't get it to log the exception detail.

**Comment by brettsam** [comment]
@brian-toniq -- are you referring to the logs in the Portal? If so, that was a bug with our FileLogger that we just fixed (https://github.com/Azure/azure-functions-host/pull/3486). Unfortunately it didn't make the cutoff for our very next release, but it will be available shortly.

**Comment by brian-toniq** [comment]
@brettsam Yes I am referring to logs in Portal, sorry I should have been more clear. Thanks for the further info and good to hear that a fix will be available soon.

**Comment by fabiocav** [comment]
@chethanrajp those errors do not seem related to the keys. If you're still experiencing this, can you please open an issue on https://github.com/Azure/azure-functions-host/issues with the details requested there for investigation?
